version.number=@project.version@
spring:
  main:
    banner-mode: off
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:earthquakes}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true